### PR TITLE
Add a BinarySpikeMonitor

### PR DESCRIPTION
**Pull request by sanjayankur31**
It does exactly as it says :)

Since the base Monitor class applied specific flags to the ofstream it
was opening, I had to modify the constructor and init methods slightly
to allow derived classes to also provide ofstream openmode flags.

Ideally, I'd have thought that each derived class would do the opening
part itself, rather than making the super do it, since the base
abstract class is more to provide a structure template?

### CODE REVIEW

**Comment by fzenke** [comment]
Looking good. You are right about the file opening part. On the other hand instead of passing filetype as an argument. Would it be possible to redefine init in the derived class?

**Comment by fzenke** [comment]
Forget what I said. Since we are calling the constructor of the superclass Monitor init will run no matter what.

**Comment by sanjayankur31** [comment]
Aye. I was looking at the init too, but since the base class's init is called no matter what, I didn't have a better way of doing it. Do you think it makes sense to move the file opening code to the derived classes themselves instead of making the base class do it? Would that be beneficial in the long run?

**Comment by fzenke** [comment]
I prefer leaving it where it is now, because most Monitors still use
ascii files for their output. Making this part of Monitor abstract,
would just require copying a lot of code to each derived classes.
However, have a look at how I altered your code to not pass the file
type as an argument, but by introducing a virtual function instead. I
like this a bit better and I hope you can live with it too.

**Comment by sanjayankur31** [comment]
Yeah. That looks good. Thanks :)

**Pull request merged**
